Softawre/Exam/Exam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from onlineapp import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
   # path('dashboard/',views.dashboardView,name="dashboard"),
    path('t_dashboard/',views.t_dashboardView,name="t_dashboard"),
    path('s_dashboard/',views.s_dashboardView,name="s_dashboard"),

    path('select/', views.selectView, name="select"),

    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name="login"),

    path('register/',views.register,name="register"),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name="logout"),

    path('student/', views.student_list, name='student_list'),
    path('teacher/', views.teacher_list, name='teacher_list'),

    path('student/upload/', views.upload_student, name='upload_student'),
    path('teacher/upload/', views.upload_teacher, name='upload_teacher'),

    path('teacher/<int:pk>/', views.delete_teacher, name='delete_teacher'),
    path('student/<int:pk>/', views.delete_student, name='delete_student'),

    path('edit_student/<int:pk>', views.edit_student, name='edit_student'),
    path('edit_teacher/<int:pk>', views.edit_teacher, name='edit_teacher'),
    path('update_student/<int:pk>', views.update_student, name='update_student'),
    path('update_teacher/<int:pk>', views.update_teacher, name='update_teacher'),

    path('admin/', admin.site.urls),
]

Softawre/Exam/onlineapp/models.py
from django.db import models



class Student(models.Model):
    s_id = models.CharField(max_length=10)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=100)
    dpt = models.CharField(max_length=50)
    phn = models.CharField(max_length=11)


class Teacher(models.Model):
    t_id = models.CharField(max_length=10)
    t_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=100)
    dpt = models.CharField(max_length=50)

Softawre/Exam/onlineapp/forms.py
from django import forms

from .models import Student,Teacher
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']



class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ("__all__")

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ("__all__")

Softawre/Exam/onlineapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.views.generic import TemplateView

from .forms import UserRegisterForm
from .forms import StudentForm,TeacherForm
from .models import Student,Teacher
from django.contrib.auth.decorators import login_required

class Home(TemplateView):
    template_name = 'home.html'

"""@login_required
def dashboardView(request):
    return render (request,'dashboard.html')"""

def t_dashboardView(request):
    return render (request,'t_dashboard.html')

def s_dashboardView(request):
    return render (request,'s_dashboard.html')


@login_required
def selectView(request):
    return render (request,'select.html')



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            form.cleaned_data.get('username')
            ##messages.success(request, f'Your account has been successfully created!Log in now')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})


@login_required
def student_list(request):
    student = Student.objects.all()
    return render(request, 'student_list.html', {
        'student': student
    })

@login_required
def teacher_list(request):
    teacher = Teacher.objects.all()
    return render(request, 'teacher_list.html', {
        'teacher': teacher
    })


@login_required
def upload_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('student_list')
    else:
        form = StudentForm()
    return render(request, 'upload_student.html', {
        'form': form
    })

@login_required
def upload_teacher(request):
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('teacher_list')
    else:
        form = TeacherForm()
    return render(request, 'upload_teacher.html', {
        'form': form
    })


@login_required
def delete_student(request, pk):
    if request.method == 'POST':
        student = Student.objects.get(pk=pk)

        student.delete()
    return redirect('student_list')

@login_required
def delete_teacher(request, pk):
    if request.method == 'POST':
        teacher = Teacher.objects.get(pk=pk)

        teacher.delete()
    return redirect('teacher_list')


@login_required
def edit_student(request, pk) :
    student = Student.objects.get(pk=pk)
    return render(request,"edit_student.html", {'student': student})

@login_required
def edit_teacher(request, pk) :
    teacher = Teacher.objects.get(pk=pk)
    return render(request,"edit_teacher.html", {'teacher': teacher})


@login_required
def update_student(request, pk) :
    student =Student.objects.get(pk=pk)
    form = StudentForm(request.POST,request.FILES, instance= student)
    if form.is_valid():
        form.save()
        return redirect('/student/')
    return render(request,"edit_student.html", {'student': student})


@login_required
def update_teacher(request, pk) :
    teacher =Teacher.objects.get(pk=pk)
    form = TeacherForm(request.POST,request.FILES, instance= teacher)
    if form.is_valid():
        form.save()
        return redirect('/teacher/')
    return render(request,"edit_teacher.html", {'teacher': teacher})

Softawre/Exam/Exam/templates/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}welcome{% endblock %}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ccb89f">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">

        <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav navbar-nav navbar-right">

        <a class="navbar-brand" href="{% url 'register' %}" >Sign Up</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        </ul>



         <ul  class="nav navbar-nav ">
            <a class="navbar-brand" href="{% url 'login' %}" >Log In</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      </ul>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Softawre/Exam/Exam/templates/edit_student.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<h1>Edit Student Info</h1>
  <form method="POST" class="post-form" action="/update_student/{{student.pk}}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">ID:</label>
            <div class="col-sm-4">
                <input type="text" name="s_id" id="id_s_id" required maxlength="10" value="{{ student.s_id }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Name:</label>
            <div class="col-sm-4">
                <input type="text" name="name" id="id_s_id" required maxlength="150" value="{{ student.name }}" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-4">
                <input type="text" name="email" id="id_s_id" required maxlength="80" value="{{ student.email }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Department:</label>
            <div class="col-sm-4">
                <input type="text" name="dpt" id="id_s_id" required maxlength="50" value="{{ student.dpt }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Contact No:</label>
            <div class="col-sm-4">
                <input type="text" name="phn" id="id_s_id" required maxlength="11" value="{{ student.phn }}" />
            </div>
        </div>

        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
</form>
{% endblock %}

Softawre/Exam/Exam/templates/edit_teacher.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
<h1>Edit Teacher Info</h1>
  <form method="POST" class="post-form" action="/update_teacher/{{teacher.pk}}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">ID:</label>
            <div class="col-sm-4">
                <input type="text" name="t_id" id="id_t_id" required maxlength="10" value="{{ teacher.t_id }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Name:</label>
            <div class="col-sm-4">
                <input type="text" name="t_name" id="id_t_id" required maxlength="150" value="{{ teacher.t_name }}" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-4">
                <input type="text" name="email" id="id_t_id" required maxlength="80" value="{{ teacher.email }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Department:</label>
            <div class="col-sm-4">
                <input type="text" name="dpt" id="id_t_id" required maxlength="50" value="{{ teacher.dpt }}" />
            </div>
        </div>


        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
</form>
{% endblock %}

Softawre/Exam/Exam/templates/home.html
{% extends "base.html" %}
{% block content %}


<h1 style="background-color:Orange;"><center>Welcome </center></h1>
<h2 style="background-color:Violet;"><center>Online Exam System </center></h2>

{% endblock %}

Softawre/Exam/Exam/templates/index.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}Welcome{% endblock %}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ccb89f">
    <div class="container-fluid">



      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">

          <li class="nav-item dropdown">

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">



          <div class="dropdown-divider"></div>

        </div>
      </li>
        </ul>


      </div>
<div >
            <a class="navbar-brand" href="{% url 'logout' %}" >Log out</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        </div>
    </div>
  </nav>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content  %}
            {% endblock %}

          </div>
        </div>
      </div>
    </div>


  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Softawre/Exam/Exam/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log in</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

Softawre/Exam/Exam/templates/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You Have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                 <a class="ml-2" href="{% url 'login' %}">login Again</a>
            </small>
        </div>
    </div>
{% endblock content %}

Softawre/Exam/Exam/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Log In</a>
            </small>
        </div>
    </div>
{% endblock content %}

Softawre/Exam/Exam/templates/s_dashboard.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}Welcome Student{% endblock %}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ccb89f">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 's_dashboard' %}" >Student_Dashboard</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">

          <li class="nav-item dropdown">

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">



          <div class="dropdown-divider"></div>

        </div>
      </li>
        </ul>


      </div>
<div >
            <a class="navbar-brand" href="{% url 'logout' %}" >Log out</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        </div>
    </div>
  </nav>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">

            <center><h1><font color="#520419" >Welcome , {{user.username}}</font></h1></center>

<p>
      <a href="{% url 'upload_student' %}" class="btn btn-primary">Add Student</a>

</p>
<p><a href="{% url 'student_list' %}" class="btn btn-primary"> Student Info</a>
</p>

          </div>
        </div>
      </div>
    </div>


  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Softawre/Exam/Exam/templates/select.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}Welcome Teacher{% endblock %}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ccb89f">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 't_dashboard' %}" >Teacher_Dashboard</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">

          <li class="nav-item dropdown">

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">



          <div class="dropdown-divider"></div>

        </div>
      </li>
        </ul>


      </div>
<div >
            <a class="navbar-brand" href="{% url 'logout' %}" >Log out</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        </div>
    </div>
  </nav>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">

           <center><h1><font color="#520419" >Welcome , {{user.username}}</font></h1></center>

<p>
<p>Who are you?</p>

     <form method="post" action="{% url 's_dashboard'  %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-success btn-md">Student</button>
            </form>
     <form method="post" action="{% url 't_dashboard'  %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger btn-md">Teacher</button>
            </form>
</p>

          </div>
        </div>
      </div>
    </div>


  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Softawre/Exam/Exam/templates/student_list.html
{% extends 'index.html' %}

{% block content %}

  {% block content_header %}
    <h2>Student Info</h2>

  {% endblock %}

  <table class="table mb-0">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
          <th>Department</th>
        <th>PhnNo</th>

        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for i in student %}
        <tr>
          <td>{{ i.s_id }}</td>
          <td>{{ i.name }}</td>
          <td>{{ i.email }}</td>
            <td>{{ i.dpt }}</td>
          <td>{{ i.phn }}</td>




          <td>
            <form method="post" action="{% url 'edit_student' i.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-success btn-md">Edit</button>
            </form>
          </td>
          <td>
            <form method="post" action="{% url 'delete_student' i.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger btn-md">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Softawre/Exam/Exam/templates/t_dashboard.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}Welcome Teacher{% endblock %}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#ccb89f">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 't_dashboard' %}" >Teacher_Dashboard</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">

          <li class="nav-item dropdown">

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">



          <div class="dropdown-divider"></div>

        </div>
      </li>
        </ul>


      </div>
<div >
            <a class="navbar-brand" href="{% url 'logout' %}" >Log out</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        </div>
    </div>
  </nav>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">

            <center><h1><font color="#520419" >Welcome , {{user.username}}</font></h1></center>

<p>
      <a href="{% url 'upload_teacher' %}" class="btn btn-primary">Add Teacher</a>

</p>
<p><a href="{% url 'teacher_list' %}" class="btn btn-primary"> Teacher Info</a>
</p>

          </div>
        </div>
      </div>
    </div>


  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>